# Generated by Django 5.2.9 on 2025-12-03 13:03

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "role")
    roles = ["admin", "public", "img"]
    for t in roles:
        Role.objects.get_or_create(title=t)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_alter_role_title'),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_code=migrations.RunPython.noop)  # dont delete the roles on undo
    ]
