# Generated by Django 5.2.9 on 2025-12-04 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('read_perm', models.CharField(choices=[('PUB', 'Public'), ('IMG', 'IMG Member'), ('PRV', 'Private')], default='PUB', max_length=3)),
                ('write_perm', models.CharField(choices=[('PUB', 'Public'), ('IMG', 'IMG Member'), ('PRV', 'Private')], default='PUB', max_length=3)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
