# Generated by Django 5.2.9 on 2025-12-15 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('TAGGED', 'Tagged'), ('LIKED', 'Liked'), ('COMMENTED', 'Commented'), ('EVENT_PHOTO_ADDED', 'Event Photo Added')], max_length=50)),
                ('target_type', models.CharField(choices=[('PHOTO', 'Photo'), ('EVENT', 'Event')], max_length=50)),
                ('target_id', models.UUIDField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx'), models.Index(fields=['recipient', '-timestamp'], name='notificatio_recipie_b8fa2a_idx'), models.Index(fields=['recipient', 'dedupe_key'], name='notificatio_recipie_7d431d_idx')],
            },
        ),
    ]
