# Generated by Django 5.2.9 on 2025-12-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photoshares_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoshares',
            name='path',
        ),
    ]
