# Generated by Django 5.2.9 on 2025-12-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_photo_id_photoshares_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoshares',
            name='allows_download',
        ),
    ]
