# Generated by Django 5.2.9 on 2025-12-09 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_rename_photoshares_photoshare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phototag',
            name='unique_tag',
        ),
        migrations.AddConstraint(
            model_name='phototag',
            constraint=models.UniqueConstraint(fields=('user', 'photo'), name='unique_tag'),
        ),
    ]
