# Generated by Django 5.2.9 on 2025-12-05 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('CO', 'Completed'), ('FA', 'Failed')], default='PE')),
                ('read_perm', models.CharField(choices=[('PUB', 'Public'), ('IMG', 'IMG Member'), ('PRV', 'Private')], default='PUB')),
                ('share_perm', models.CharField(choices=[('OR', 'Owner or Roles'), ('AN', 'Anyone'), ('DI', 'Disabled')], default='OR')),
                ('downloads', models.BigIntegerField(default=0)),
                ('views', models.BigIntegerField(default=0)),
                ('original_path', models.TextField(default='')),
                ('thumbnail_path', models.TextField(default='')),
                ('watermarked_path', models.TextField(default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoShares',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_key', models.CharField(choices=[('W', 'Watermarked'), ('O', 'Original')], default='O')),
                ('allows_download', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'photo_id'), name='unique_tag')],
            },
        ),
    ]
