# Generated by Django 5.2.9 on 2025-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoshares',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
