# Generated by Django 5.2.9 on 2025-12-07 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photoshares_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoshares',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='phototags',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='phototags',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='tagged_users',
            field=models.ManyToManyField(related_name='tagged_photos', through='photos.PhotoTags', to=settings.AUTH_USER_MODEL),
        ),
    ]
