# Generated by Django 5.2.9 on 2025-12-08 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photoshares_allows_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoShares',
            new_name='PhotoShare',
        ),
        migrations.RenameModel(
            old_name='PhotoTags',
            new_name='PhotoTag',
        ),
    ]
