# Generated by Django 5.2.9 on 2025-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_created_at_photo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='auto_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_tags',
            field=models.JSONField(default=list),
        ),
    ]
