# Generated by Django 5.2.9 on 2026-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_auto_tags_photo_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processing_errors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
