# Generated by Django 5.2.9 on 2026-01-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_processing_errors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnail_path',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='watermarked_path',
            new_name='watermarked_url',
        ),
    ]
