# Generated by Django 5.2.9 on 2026-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_alter_photo_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='clip_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
