# Generated by Django 5.2.9 on 2026-06-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_coordinator'),
        ('photos', '0014_photo_clip_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event'),
        ),
    ]
